### ISSUE TITLE
Convert to Xamarin Forms

### ISSUE THREAD

**Issue by hjerpbakk** [Illedan/PartyfyYou#1]
Such that I can use the app on my Mac

**Comment by simonkaspersen** [comment]
Or electron-app that only lives in the Tray

**Comment by simonkaspersen** [comment]
I ment Menu-bar or Touchbar

**Comment by hjerpbakk** [comment]
Only a foreground app may control the contents of the touch bar

**Comment by Illedan** [comment]
This app is supposed to be fullscreen. Agreed on the Xamarin-Forms points, but electron app in touchbar showing a YouTube-video is kinda useless..
I would prefer separate issues for each request.

**Comment by simonkaspersen** [comment]
Was thinking more about a control-center. With some info about the song and a option to open a full screen video. Or toggling of auto-open or touch to open

**Comment by Illedan** [comment]
Since it's converted to a webapp, it now supports mac viewing. Closing this.
